language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  
env:
  - DB=mysql 
  
  
before_script: 
 - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS agenda;'; fi"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
 - php -S localhost:8000 -t public/ &

script:
  - "java -jar selenium-server-standalone-2.31.0.jar -htmlSuite *firefox http://localhost:8000/ /home/travis/build/JoyceLA/AgendarCirugias/TestSelenium/PruebaCrearCuenta.php ./result"
  - "php -r 'echo strip_tags(file_get_contents(\"result\"));'"
