language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  
env:
  - DB=mysql 
  
  
before_script: 
 - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS agenda;'; fi"
 - sh -e /etc/init.d/xvfb start
 - export DISPLAY=:99.0
 - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.15.0.jar
 - java -jar selenium-server-standalone-2.15.0.jar > /dev/null 2>&1 &
 - sleep 30  # to wait for Selenium to be up and running
