language: php
php:
  - 5.2
  - 5.3
before_script: ./before_script.sh
script: "php run-phpunit.php"
env:
  - DB=mysql
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS agenda;'; fi"
  
